docs/source/index.rst, docs/source/tagset.rst
Correções feitas tagset:
Correção em exemplo de abbrev-journal-title (foi inserido reticências);
<publisher-loc> retirado de "Aparece em" do elemento <publisher-loc>
Retirado informações de 3.0;
Incluído: Label aparece em boxed-text;
Correção em "Ocorre" de "<trans-title>. Mudei para "Uma vez". (Regra - mas acredito que já é validada)
Acrescentado valor "original" em <institution> com breve descrição #126;
Corrigido exemplos de <pub-date> (estavam invertidos);
Em <season> foi acrescentado a informação de intervalo de meses do ano;
<funding-group> mudar "Está" para "Esta"
Retirar frase: "... e em :ref:`elemento-front`" do funding-statement
<fn-group> - ver asteriscos de <label>;
Inserir <boxed-text> e <glossary> no "Aparece em" de <fig>.
Adicionar elemento <person-group> em "Aparece em" de …
=> closes #126; closes #125; closes #124; closes #123; closes #121

docs/source/tagset.rst
Foi excluído o segundo exemplo em `<sig-block>` por entendermos que eram duas maneiras diferentes para representar a mesma coisa conforme ticket aberto #80 por @RPostalli . Além disso alterou-se a nota do mesmo elemento. Havia um erro que juntava duas palavras.
=> Excluir exemplo 2 em <sig-block>

docs/source/tagset.rst
```<award-group>``` aparece 1 ou + vezes
=> close on issue #135

docs/source/tagset.rst
alterado a nota: "```<funding-group>``` deve ser inserida entre as tags ```<kwd-group>``` e ```<counts>```."
Para:
```<funding-group>``` deve ser inserida antes de ```<counts>```.
=> Corrigir informação de posição em <funding-group> close #136

docs/source/glossary.rst, docs/source/tagset.rst
Esta atividade tem o objetivo de entrar em conformidade com a
terminologia adotada oficialmente pelo programa SciELO.
Closes #131
=> Substituição da palavra "revista" por "periódico".

docs/source/tagset/elemento-product.rst
Correção no exemplo do ```<inline-graphic>``` da tag ```<product>```.
=> correcao na tag inline-graphic de product

docs/source/tagset/elemento-country.rst, docs/source/tagset/elemento-related-article.rst
Inclusão de nota sobre ```<country>``` em arquivos de tradução.
=> Inclusão de nota sobre 'country' em translation

docs/source/index.rst
A incorporação desse pull request deve ser revertida pelos motivos:
* Não corresponde de fato à entrega da primeira semana de trabalho, mas apenas ao exemplo do fluxo de trabalho.
* Além da correção envolvendo a vírgula, o editor de texto incluiu BOM (Byte order mark) UTF-8 no arquivo -- aparentemente é o comportamento padrão de vários produtos Microsoft.
=> Revert "correção de pontuação em notas de versão"

docs/source/tagset/elemento-caption.rst
Inclusão de elemento em 'Aparece em' de ```<caption>```.
=> inclusao de elemento em 'Aparece em' de <caption>, fix #320

docs/source/tagset/elemento-contrib-group.rst
Retirado elemento ```<collab>``` do 'Aparece em' e incluído o elemento ```<front-stub>```
=> Retirado elemento <collab> do 'Aparece em' e incluído o elemento <front-stub>, fix #325

docs/source/tagset/elemento-contrib-id.rst
Inclusão de atributo no elemento ```<contrib>``` do exemplo.
=> inclusao de atributo no elemento <contrib> do exemplo, Fix #326

docs/source/tagset/elemento-month.rst
Ordenação dos elementos de ```<month>``` em 'Aparece em' e reestruturação dos exemplos.
=> Ordenação dos elementos de <month> em 'Aparece em' e reestruturação dos exemplos. Fix #345

docs/source/tagset/elemento-season.rst
Ordenação dos elementos de ```<season>``` no 'Aparece em'
=> Ordenação dos elementos de <season> no 'Aparece em'. Fix #351

docs/source/tagset/elemento-sec.rst
Ordenação dos elementos em ```<sec>``` e reestruturação dos exemplos.
=> Ordenação dos elementos em <sec> e reestruturação dos exemplos. Fix #352

docs/source/tagset/elemento-source.rst
ordenação dos elementos de ```<source>``` em 'Aparece em' e correção na regra 'Ocorre'.
=> ordenação dos elementos de <source> em 'Aparece em' e correção na regra 'Ocorre'. Fix #354

docs/source/tagset/elemento-volume.rst
corrige regra de ocorrencia de ```<volume>```.
=> corrige regra de ocorrencia de <volume>. Fix #357

docs/source/tagset/elemento-suffix.rst
Correção em ```<suffix>``` na regra de 'Ocorre'.
=> Correção em <suffix> na regra de 'Ocorre'. Fix #358

docs/source/tagset/elemento-title-group.rst
Inclusão de exemplos de título em ```<title-group>```.
=> Inclusão de exemplos de título em <title-group>. Fix #363

docs/source/tagset/elemento-xref.rst
Ordenação dos elementos de ```<xref>``` no 'Aparece em' e reestruturação dos exemplos.
=> Ordenação dos elementos de <xref> no 'Aparece em' e reestruturação dos exemplos. Fixes #365

docs/source/tagset/elemento-xref.rst
Inclusão do elemento ```<sec>``` no 'Aparece em' de ```<xref>```.
=> Inclusão do elemento <sec> no 'Aparece em' de <xref>. Fixes # 367

docs/source/tagset/elemento-year.rst
Ordenação dos elementos de ```<year>``` no 'Aparece em'
=> Ordenação dos elementos de <year> no 'Aparece em'. Fixes #368

docs/source/tagset/elemento-ref-list.rst
Permitir elemento ```<label>``` em ```<ref-lits>``` e inserção de exemplos
=> Permitir elemento <label> em <ref-lits> e inserção de exemplos. Fix #372

docs/source/tagset/elemento-caption.rst
Reestruturação de exemplos de ```<caption>```.
=> Reestruturação de exemplos de <caption>

docs/source/tagset/elemento-ext-link.rst
inclusao de elemento no 'Aparece em' de ```<ext-link>```.
=> inclusao de elemento no 'Aparece em' de <ext-link>. Fixes #333

docs/source/tagset/elemento-volume.rst
Inclusão de elemento no 'Aparece em' de ```<volume>```.
=> Inclusão de elemento no 'Aparece em' de <volume>. Fixes # 355

docs/source/tagset/elemento-inline-graphic.rst, docs/source/tagset/sugestao-atribuicao-id.rst
Correção em texto sobre ```<inline-graphic>```. O elemento identifica ícones que estão como imagem em linha e não *equações*.
=> Correção em texto sobre <inline-graphic>. Fix #359

docs/source/narr/regra-nomeacao.rst
Exclusão do sinal 'dois pontos' no título de cada link da regra de nomeação
=> Exclusão do sinal 'dois pontos' no título de cada link da regra de nomeação

docs/source/narr/regra-nomeacao.rst
Exclusão de 'dois pontos' em 'Número especial'
=> Exclusão de 'dois pontos' em 'Número especial'

docs/source/tagset/elemento-product.rst
Corrige exemplos e informações sobre tipos de  ```<product>```.
=> Corrige exemplos e informações sobre tipos de  <product>

docs/source/glossary.rst, docs/source/index.rst, docs/source/narr/regra-nomeacao.rst, docs/source/tagset/elemento-contrib-group.rst, docs/source/tagset/elemento-disp-formula.rst, docs/source/tagset/elemento-fig.rst, docs/source/tagset/elemento-fn.rst, docs/source/tagset/elemento-front.rst, docs/source/tagset/elemento-funding-group.rst, docs/source/tagset/elemento-history.rst, docs/source/tagset/elemento-issue.rst, docs/source/tagset/elemento-subj-group.rst
Correção nos tópicos:
* glossary
* index
* regra de nomeação
* contrib-group
* disp-formula
* fig
* fn
* fpage
* front-stub
* front
* funding-group
* history
* issue
=> Correção nos tópicos do guia SciELO Publishing Schema 1.5

docs/source/narr/ensaio-clinico.rst, docs/source/tagset/elemento-ext-link.rst
Em Ensaio Clínico o valor de ``@ext-link-type"" foi alterado para "clinical-trial".
Relacionado ao ticket #242 .
=> Correção em valor de ext-link-type de Ensaio Clínico

docs/source/tagset/elemento-ref-list.rst
Fixes #486 acrescenta ref-list  em "aparece em" do elemento ref-list
=> Incluído ref-list em aparece em em ref-list.

docs/source/narr/aheadofprint.rst
Fixes #240 aceita qualquer valor em article-type para artigos publicados na modalidade AOP.
=> Exclui obrigatoriedade do valor research-article em article-type

docs/source/tagset/xml-doctype.rst
Fixes #489 incluindo a URL no system id.
=> Utilizar URL absoluta do *system id*, na declaração de DOCTYPE

docs/source/tagset/elemento-product.rst
=> *CDATA* como filho do elemento *name* invalida o doc em relação a JATS

docs/source/whatsnew-1.6.rst
Retirados de "correção de exemplos de uso e estilo de redação" os tickets #489 e #486, pois já estavam listados abaixo.
=> Retirados de "correção de exemplos de uso e estilo de redação" os tickets #489 e #486

docs/source/narr/scielo-brasil.rst
Acrescenta a obrigatoriedade de  ```<contrib-id contrib-id-type="orcid">``` em Regras Específicas para SciELO Brasil.
Após elemento ```<product>```
Acrescentado nota informando que para Errata e Retratação o elemento não é obrigatório, já que errata e retratação não terá autoria.
#634
=> Acrescenta a obrigatoriedade de <contrib-id contrib-id-type="orcid"> em Regras Específicas para SciELO Brasil.

docs/source/index.rst, docs/source/narr/taxonomia-credit.rst, docs/source/tagset/elemento-contrib.rst, docs/source/tagset/elemento-role.rst, docs/source/whatsnew-1.10.rst
Adiciona documentação narrativa sobre a representação de informação
sobre contribuição dos autores de acordo com a taxonomia CrediT. O texto
foi baseado na recomendação da JATS4R disponível em https://jats4r.org/credit-taxonomy
O texto está sendo trabalhado em https://docs.google.com/document/d/1UwHgZc-99cnRlg5lfbLMPAbfWmDLmgMYY1fxgdh9ScI/edit?usp=sharing
n/a
n/a
#821 
- JATS4R CRediT Taxonomy Guidelines: https://jats4r.org/credit-taxonomy
- NISO JATS 1.1: http://jats.nlm.nih.gov/publishing/tag-library/1.1/
- CASRAI Contributor Roles: https://dictionary.casrai.org/Contributor_Roles
- CRediT: Contributor Role Taxonomy - Going beyond authorship: https://docs.google.com/document/d/1aJxrQXYHW5U6By3KEAHrx1Iho6ioeh3ohNsRMwsoGPM
=> Adiciona contribuição dos autores
