scieloorg/scielo_publishing_schema

- docs/source/tagset.rst
Substituido @xref por xref.
fix #60
> Correção de conteúdo descritivo do elemento xref

- docs/source/narr/regra-de-nomeação-arquivos
- docs/source/tagset.rst
inserção de regra de nomeação para 98% dos tipos suportados pelo SciELO
e correções na tagset.
> Add regra de nomeação de arquivos na doc narrativa

- docs/source/tagset.rst
Inserção das licenças IGO em tipos de licenças aceitas
> Inserção das licenças IGO

- docs/source/tagset.rst
Retirado informação de @specific-use="display-only" e um exemplo de
referência com esse atributo.
> Retirado informação de "display-only"

- docs/source/index.rst
Retirar informação de PMC em lista de elementos
> closes on issue #133

- docs/source/tagset.rst
Corrigir todas as informações "Obrigatoriamente, deve.." para apenas: "deve...".
> Corrigir todas as informações 'Obrigatoriamente, deve..' close #137

- docs/source/glossary.rst
- docs/source/narr/errata.rst
- docs/source/narr/regra-nomeacao.rst
- docs/source/tagset.rst
Esta atividade tem o objetivo de entrar em conformidade com a
terminologia adotada oficialmente pelo programa SciELO.
Closes #130
> Substituição da palavra "fascículo" por "número".

- docs/source/tagset.rst
Closes #185
A implementação está conforme descrito em
https://github.com/scieloorg/scielo_publishing_schema/issues/185#issuecomment-169992208
> Suporte a diferentes protocolos em *ext-link*.

- docs/source/narr/caracteres.rst
Inserido link para a tabela de caracteres Unicode
> Inserido link para a tabela de caracteres Unicode

- docs/source/index.rst
> correção de pontuação em notas de versão

- docs/source/tagset/elemento-related-article.rst
Acrescentando valores em ``@related-article-type``. Foi inserido os seguintes valores:
- letter
- partial-retraction
- retraction-article
- translated-article
> Acrescentando valores em @related-article-type

- docs/source/narr/regra-nomeacao.rst
Acrescentar regra de nomeação de arquivos  relacionado ao #317, #210
> Acrescentar tipos na Regra de nomeação de arquivos

- docs/source/tagset/elemento-ext-link.rst
Inclusão de valores possíveis no ``@extlink-type`` .
> Inclusão de valores possíveis no @ext-link-type

- docs/source/tagset/elemento-supplementary-material.rst
Inclusão de elementos no "Aparece em" de Material Suplementar.
> Inclusão de elementos no "Aparece em" do Material Suplementar.

- docs/source/tagset/elemento-caption.rst
Inclusão de elemento ```<p>``` em ```<caption>``` de figura.
> Inclusão de elemento <p> em <caption> de figura, fixes #259

- docs/source/tagset/elemento-back.rst
Inclusão de elementos no "Aparece em" de Back
> Inclusão de elementos no Aparece em de Back, fixes #318

- docs/source/tagset/elemento-disp-formula.rst
- docs/source/tagset/elemento-fig.rst
- docs/source/tagset/elemento-table.rst
Inclusão de nota sobre posição dos ativos digitais.
> Inclusão de nota sobre posição dos ativos digitais, fixes #319

- docs/source/tagset/elemento-disp-formula.rst
Alteração da equação codificada em ```<disp-formula>```.
> alteração da equação codificada em <disp-formula>, Fix #327

- docs/source/tagset/elemento-disp-quote.rst
Acrescentando elementos no 'Aparece em' do ```<disp-quote>```.
> Acrescentando elementos no 'Aparece em' do <disp-quote>, Fix #328

- docs/source/tagset/elemento-element-citation.rst
Alteração na regra de ocorrência para Ocorre Uma vez
> Alteração na regra de ocorrencia para Ocorre Uma vez. Fix #330

- docs/source/tagset/elemento-front-stub.rst
Alteração do exemplo de ```<front-stub>```.
> Alteração do exemplo de <front-stub>. Fix #335

- docs/source/tagset/elemento-funding-group.rst
Inclusão de exemplo de ```<funding-group```> e add informação sobre a posição do elemento ```<funding-group>```.
> Inclusão de exemplo de <funding-group> e add informação sobre a posição do elemento <funding-group>

- docs/source/tagset/elemento-given-names.rst
alteração na regra de ocorrencia. de Zero ou mais vezes Para:
Zero ou uma vez.
> alteração na regra de ocorrencia. Fix #337

- docs/source/tagset/elemento-inline-formula.rst
Exclusão do parágrafo sobre ID
> Exclusão do parágrafo sobre ID. Fix #338

- docs/source/tagset/elemento-institution.rst
Alteração de exemplo de institution
> Alteração de exemplo de institution. Fix #339

- docs/source/tagset/elemento-issn.rst
Inclusão de exemplo de ISSN em referência bibliográfica
> Inclusão de exemplo de ISSN em referência bibliográfica. Fix #340

- docs/source/tagset/elemento-issue.rst
correção na informação de Ocorrencia e reestruturação dos exemplos
> correção na informação de Ocorrencia e reestruturação dos exemplos. Fix #341

- docs/source/tagset/elemento-label.rst
Inserção dos elemento em ordem alfabética e reestruturação dos exemplos.
> Inserção dos elemento em ordem alfabética e reestruturação dos exemplos. Fix #342

- docs/source/tagset/elemento-list.rst
Organização dos elementos em 'Aparece em' do list
> Organização dos elementos em 'Aparece em' do <list>. Fix #343

- docs/source/tagset/elemento-media.rst
Ordenação de elemento no 'Aparece em' e inclusão de outros e reestruturação de exemplos em ```<media>```.
> <media> Ordenação de elemento no 'Aparece em' e inclusão de outros e reestruturação de exemplos. Fix #344

- docs/source/tagset/elemento-page-range.rst
Ordenação dos elementos em 'Aparece em' do ```<page-range>```.
> Ordenação dos elementos em 'Aparece em' do <page-range>. Fix #346

- docs/source/tagset/elemento-person-group.rst
Ordenação dos elementos de ```<person-group>``` em 'Aparece em'
> Ordenação dos elementos de <person-group> em 'Aparece em'. Fix #347

- docs/source/tagset/elemento-publisher-loc.rst
Ordenação dos elementos em 'Aparece em' de ```<person-group>```
> Ordenação dos elementos em 'Aparece em' de <person-group>. Fix #349

- docs/source/tagset/elemento-publisher-name.rst
Ordenação dos elementos de ```<publisher-name>``` em 'Aparece em' e Reestruturação dos exemplos.
> Ordenação dos elementos de <publisher-name> em 'Aparece em' e Reestruturação dos exemplos. Fix #350

- docs/source/tagset/elemento-size.rst
ordenação dos elementos de ```<size>``` em 'Aparece em' e alteração de regra em 'Ocorre'.
> ordenação dos elementos de <size> em 'Aparece em' e alteração de regra em 'Ocorre'. Fix #353

- docs/source/tagset/elemento-supplementary-material.rst
Reestruturação de exemplos de ```<supplementary-material>```.
> Reestruturação de exemplos do material suplementar

- docs/source/tagset/elemento-surname.rst
Correção em regra de ocorrência de ```<surname>```.
> Correção em regra de ocorrência de <surname>. Fix #360

- docs/source/tagset/elemento-table.rst
Inclusão de quadro descritivo, exemplo de tabela simples codificada e reestruturação de tabelas com legendas traduzidas.
> Inclusão de quadro descritivo, exemplo de tabela simples codificada e reestruturação de tabelas com legendas traduzidas. Fix #362

- docs/source/tagset/elemento-trans-title-group.rst
Inclusão de exemplo de ```<trans-title-group>```
> Inclusão de exemplo de <trans-title-group>. Fix #364

- docs/source/tagset/xml-doctype.rst
Reestruturação de exemplos de elementos flutuantes
> Reestruturação de exemplos de elementos flutuantes. Fixes #366

- docs/source/tagset/elemento-year.rst
Alteração na regra de 'Ocorre' em ```<year>``` e inclusão de exemplos
> Alteração na regra de 'Ocorre' em <year> e inclusão de exemplos. Fixes #370, #371 

- docs/source/tagset/elemento-caption.rst
- docs/source/tagset/elemento-disp-formula.rst
- docs/source/tagset/elemento-issue.rst
- docs/source/tagset/elemento-table.rst
- docs/source/tagset/xml-doctype.rst
Correção dos tópicos:
- caption
- disp-formula
- issue
- table
- doctype
> Correção de outros elementos do guia

- docs/source/tagset/elemento-table.rst
> corrige formatação de tabela

- docs/source/tagset/elemento-table.rst
> correcao 2 na tabela

- docs/source/tagset/elemento-caption.rst
- docs/source/tagset/elemento-issn.rst
> correções teste

- docs/source/tagset/elemento-issue.rst
- docs/source/tagset/elemento-label.rst
- docs/source/tagset/xml-doctype.rst
Correção na formatação das referências de listagem de exemplos
> Correção na formatação das referências de listagem de exemplos

- docs/source/tagset/elemento-ref-list.rst
- docs/source/tagset/elemento-sec.rst
- docs/source/tagset/elemento-xref.rst
- docs/source/tagset/elemento-year.rst
correção na formatação dos exemplos listados:
- ref-list
- sec
- xref
- year
> correção na formatação dos exemplos listados

- docs/source/tagset/elemento-sec.rst
corrige palavra em item de sec sem tipo padrão
> corrige palavra em item de sec sem tipo padrão

- docs/source/tagset/elemento-ref-list.rst
> corrige codigo de bloco

- docs/source/tagset/elemento-sec.rst
> corrige exemplo de seção

- docs/source/tagset/elemento-article-title.rst
- docs/source/tagset/elemento-boxed-text.rst
- docs/source/tagset/elemento-collab.rst
- docs/source/tagset/elemento-date-in-citation.rst
- docs/source/tagset/elemento-def-list.rst
- docs/source/tagset/elemento-role.rst
> reestruturação de exemplos

- docs/source/tagset/elemento-edition.rst
- docs/source/tagset/elemento-email.rst
- docs/source/tagset/elemento-funding-source.rst
- docs/source/tagset/elemento-glossary.rst
- docs/source/tagset/elemento-name.rst
- docs/source/tagset/elemento-pub-date.rst
Reestruturação de exemplos dos tópicos:
* edition
* email
* funding-source
* glossary
* name
* pub-date
> Reestruturação de exemplos dos tópicos do tagset

- docs/source/tagset/elemento-season.rst
- docs/source/tagset/elemento-subj-group.rst
- docs/source/tagset/elemento-trans-abstract.rst
Reestruturação de exemplos nos tópicos:
* subj-group
* trans-abstract
* season
> Reestruturação de exemplos nos tópicos do tagset 2

- docs/source/narr/regra-nomeacao.rst
Reestruturação de exemplos de Regra de nomeação
> Reestruturação de exemplos de Regra de nomeação

- docs/source/narr/regra-nomeacao.rst
correção na estrutura dos exemplos
> correção na estrutura dos exemplos

- docs/source/narr/regra-nomeacao.rst
Correção na formatação da ultima lista de casos especiais
> Correção na formatação da ultima lista de casos especiais

- docs/source/narr/regra-nomeacao.rst
corrige exemplo de Caso Especial em Regra de Nomeação
> corrige exemplo de Caso Especial em Regra de Nomeação

- docs/source/tagset/elemento-inline-graphic.rst
Retirado frase sobre Sugestao de Atribuiçao de id de inline-graphic
> Retirado frase sobre Sugestao de Atribuiçao de id de inline-graphic

- docs/source/tagset/elemento-inline-graphic.rst
> Corrige, fecha ticket. FIXED #222

- docs/source/tagset/elemento-product.rst
Inclusão de exemplo de product diferente do tipo book
> Inclusão de exemplo de product diferente do tipo book. FIXED #257

- docs/source/tagset/elemento-product.rst
> corrige formatação de exemplo

- docs/source/tagset/elemento-product.rst
Inclusão de exemplo e correção na tabela de valores possíveis em ```<product>```.
> Inclusão de exemplo e correção na tabela de valores possíveis em <product>

- docs/source/index.rst
- docs/source/narr/scielo-brasil.rst
- docs/source/tagset/elemento-article-id.rst
- docs/source/tagset/elemento-license.rst
Inclusão de seção 'Regras SciELO Brasil' e correção nos tópicos article-id e license.
> Inclusão de seção 'Regras SciELO Brasil' e correção nos tópicos article-id e license. Fixes #373, #198

- docs/source/tagset/elemento-article-id.rst
- docs/source/tagset/elemento-license.rst
Corrige formatação dos  tópicos
> Corrige formatação dos  tópicos

- docs/source/narr/scielo-brasil.rst
Correção na descrição da seção SciELO Brasil.
> Correção na descrição da seção SciELO Brasil.

- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-related-article.rst
Inclusão do tipo 'partial-retraction' em <article> ecorreção na descrição de retraction em <related-article>.
> Inclusão do tipo 'partial-retraction' em <article> ecorreção na descrição de retraction em <related-article>. Fixes #459

- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-related-article.rst
Correção na descrição do restraction en related-article e no termo partial-retraction em article.
> Correção na descrição do restraction en related-article e no termo partial-retraction em article.

- docs/source/tagset/elemento-related-article.rst
corrige descrição em partial-retraction de ```<related-article>```.
> corrige descrição em partial-retraction de <related-article>

- docs/source/index.rst
- docs/source/narr/ensaio-clinico.rst
- docs/source/tagset/elemento-subj-group.rst
Organização dos elementos da FAQ
> Organização dos elementos da FAQ

- docs/source/tagset/elemento-subj-group.rst
Correção na formatação das seções do ```<subject>```
> Correção na formatação das seções do <subject>

- docs/source/tagset/elemento-subj-group.rst
Inclusão do elemento ```<subj-group>``` no 'Aparece em' de ```<subj-group>```
> Inclusão do elemento <subj-group> no 'Aparece em' de <subj-group>. Fixes #356

- docs/source/tagset/elemento-subj-group.rst
correção em informação de nota de ```<subject-group>```
> correção em informação de nota de <subject-group>

- docs/source/glossary.rst
- docs/source/narr/ensaio-clinico.rst
- docs/source/tagset/elemento-subj-group.rst
* Correção em informação de Ensaio Clínico no tópico ensaio clinico da documentação narrativa
* Correção na informação de Ensaio Clinico no glossário
> Atualiza recomendações para ensaios clínicos e elemento subj-group.

- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-product.rst
- docs/source/tagset/elemento-ref-list.rst
- docs/source/tagset/elemento-related-article.rst
Correção nos elementos ```<article>```, ```<product>```, ```<ref-list>``` e ```<related-article>```.
> Correção nos elementos <article>, <product>, <ref-list> e <related-article>.

- docs/source/whatsnew-1.5.rst
Inclusao do Whatsnew do SciELO PS 1.5
> Inclusao do Whatsnew do SciELO PS 1.5

- docs/source/whatsnew-1.5.rst
Inserção de espaço entre asterisco e palavra 'Alterada'
> Inserção de espaço entre asterisco e palavra 'Alterada'

- docs/source/tagset/elemento-subj-group.rst
Correção do nível de seção do tópico 'subseção em documentos' em ```<subj-group>```.
> Correção do nível de seção do tópico 'subseção em documentos' em subj-group

- docs/source/narr/scielo-brasil.rst
Fixes #510 Inclui obrigatoriedade de histórico, corrige sintaxe de texto em rst.
> Inclui obrigatoriedade de histórico e corrige sintaxe

- docs/source/tagset/elemento-elocation-id.rst
> Ajusta texto do elocation-id

- docs/source/narr/artigo-comentado.rst
Fixes #254 altera artigo comentado para comentários de artigo e inclui redação de acordo com a JATS.
> Altera texto de Artigo Comentado

- docs/source/whatsnew-1.6.rst
> Adiciona resumo das alterações da versão 1.6 do SciELO PS

- docs/source/narr/scielo-brasil.rst
> Corrige regras SciELO Brasil

- docs/source/narr/aheadofprint.rst
- docs/source/narr/tipos-especiais-documentos.rst
- docs/source/tagset/elemento-media.rst
- docs/source/tagset/elemento-subj-group.rst
> Corrige exemplo de <media> e retira restrição de seção para AOP

- docs/source/narr/retratacao.rst
- docs/source/narr/tipos-especiais-documentos.rst
- docs/source/tagset/elemento-alternatives.rst
- docs/source/tagset/elemento-app.rst
- docs/source/tagset/elemento-article-categories.rst
- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-author-notes.rst
- docs/source/tagset/elemento-funding-statement.rst
- docs/source/tagset/elemento-history.rst
- docs/source/tagset/elemento-kwd-group.rst
As alterações fecham os tickets:
Fixes #531
Fixes #530
Fixes #524
Fixes #523 --- já estava resolvido
Fixes #490 --- já estava resolvido
Fixes #231
Resolve parcialmente:
#533
> Criação da página de Retratação + Resolução de tickets

- docs/source/tagset/elemento-fn.rst
- docs/source/tagset/elemento-table-wrap-foot.rst
> Correção de documentação

- docs/source/tagset/elemento-list.rst
> Correção do exemplo em <list>

- docs/source/index.rst
- docs/source/tagset/xml-doctype.rst
> Adiciona o exemplo da JATS 1.1 ao elemento <!DOCTYPE>

- docs/source/index.rst
- docs/source/tagset/elemento-app.rst
- docs/source/tagset/elemento-issue.rst
- docs/source/tagset/elemento-postal-code.rst
- docs/source/tagset/elemento-state.rst
> Adição de elemento <postal-code> e adição de exemplo em <issue>

- docs/source/tagset/elemento-city.rst
- docs/source/tagset/elemento-data-title.rst
- docs/source/tagset/elemento-postal-code.rst
- docs/source/tagset/elemento-state.rst
- docs/source/tagset/elemento-version.rst
Inclui nota sobre versão relacionada ao elemento.
> Fixed #560

- docs/source/tagset/elemento-contrib-group.rst
Corrige ocorrência do elemento contrib-group
> Fixes #599

- docs/source/narr/scielo-brasil.rst
> Fixes #594 Alteração de regras específicas para SciELO BR

- docs/source/index.rst
> Alteração em nota de versão

- docs/source/tagset/elemento-date.rst
> Fixes #527 Alteração de atributos de Date

- docs/source/tagset/elemento-permissions.rst
Corrige ocorrência do elemento permissions
> Fixes #575

- docs/source/tagset/elemento-name.rst
Corrige ocorrência do elemento name
> Fixes #574

- docs/source/tagset/elemento-caption.rst
Alterar ocorrência no elemento caption.
> Fixes #569

- docs/source/tagset/elemento-article-title.rst
> Fixes #568

- docs/source/narr/scielo-brasil.rst
Fixes #604 - Insere <product> em RESB
> Fixes #604

- docs/source/tagset/elemento-product.rst
Fixes #605 - Corrige especificações da tag <product>
> Fixes #605

- docs/source/tagset/elemento-product.rst
Altera valores possíveis para product-type
> Fixes #610

- docs/source/tagset/elemento-subj-group.rst
Corrige notas em ```<subj-group>```
> Fixes #612

- docs/source/tagset/elemento-article-title.rst
Corrige notas em article-title
> Fixes #616

- docs/source/tagset/elemento-article.rst
Acrescenta exemplo da tag com DTD 1.1
> Fixes #613

- docs/source/tagset/elemento-elocation-id.rst
> Fixes #618

- docs/source/tagset/elemento-trans-title.rst
Corrige texto e acrescenta nota para trans-title
> Fixes #617

- docs/source/tagset/elemento-back.rst
Corrige tabela em ```<back>```
> Fixes #627

- docs/source/tagset/elemento-body.rst
Altera texto em ```<body>``` e corrige nota.
> Fixes #628

- docs/source/tagset/elemento-funding-source.rst
Melhoria em ```funding-group```
> Fixes #629

- docs/source/tagset/elemento-funding-statement.rst
Melhoria em ```<funding-statement>```
> Fixes #630

- docs/source/tagset/elemento-fn.rst
> Fixes #626

- docs/source/narr/artigo-dados.rst
- docs/source/narr/tipos-especiais-documentos.rst
Acrescenta na documentação narrativa o documento artigo-dados.rst e em Tipos especiais de Documentos.
#834
> Insere Artigo de dados em Tipos especiais de documentos

- docs/source/reference.rst
Acrescenta e corrige referências no SPS
#811
> Fixes #881 Acrescenta e corrige referências

- docs/source/narr/ensaio-clinico.rst
Corrige link que estava quebrado da "Sociedade Brasileira de Profissionais em Pesquisa Clínica" na documentação narrativa Ensaio Clínico.
#882
> Fixes #882 Corrige link em Ensaio Clínico

- docs/source/index.rst
- docs/source/whatsnew-1.10.rst
Altera textos prefaciais para lançamento 1.10 e acrescenta o documento "O que há de novo" que deverá ser alterado em #877 .
#878
> Fixes #878 Altera textos prefaciais para lançamento 1.10

- docs/source/tagset/elemento-abstract.rst
Documenta em `<abstract>` o uso de HIGHLIGHTS.
NA
Encontra-se documentado no ticket.
NA
#864 
NA
> Documenta HIGHLIGHTS

- docs/source/tagset/elemento-fn.rst
Atualização do texto de @fn-type="financial-disclosure"
Na tabela dos tipos financial-disclosure e supported-by
Descrito no ticket.
NA
https://github.com/scieloorg/scielo_publishing_schema/issues/859
NA
> Atualização do texto de @fn-type="financial-disclosure"

- docs/source/glossary.rst
Acrescenta termos no glossário
Nos temos: 
JATS4R: 
CREDIT: 
CASRAI: 
ORCID: 
Taxonomia:
Highlights: 
NA
NA
https://github.com/scieloorg/scielo_publishing_schema/issues/879
https://docs.google.com/document/d/1ImjUDzxP8eiszWkbTdaL_l0rjQiACWzqhtG2Gdcf9sM/edit?ts=5df2a9d4
> Acréscimo de termos no Glossário

- docs/source/tagset/elemento-contrib-id.rst
Acrescenta link da tag com Regras Específicas para SciELO Brasil
Primeira linha de `<contrib-id>`
https://github.com/scieloorg/scielo_publishing_schema/issues/634
NA
https://github.com/scieloorg/scielo_publishing_schema/issues/891
NAt.
> Correção em <contrib-id> (link para RESB)

- docs/source/reference.rst
Acrescenta duas novas refs.
ref: IBRAHIM, Andrew M. Use of a visual abstract to disseminate scientific research. University of Michigan, 2018, version 4. Disponível em: <https://static1.squarespace.com/static/5854aaa044024321a353bb0d/t/5a527aa89140b76bbfb2028a/1515354827682/VisualAbstract_Primer_v4_1.pdf>.
ref: INTERNATIONAL ORGANIZATION FOR STANDARDIZATION. ISO 639-1 - Language Codes, 2012. Disponível em: <http://www.mathguide.de/info/tools/languagecode.html>.
NA
NA
#881 
NA
> Acrescenta duas novas referências

- docs/source/glossary.rst
- docs/source/tagset/elemento-contrib.rst
- docs/source/tagset/elemento-fn.rst
- docs/source/tagset/elemento-person-group.rst
- docs/source/tagset/elemento-surname.rst
Corrigi regra disponível em contrib para contrib-type abarcando todos os tipos e não mais restringindo ai tipo author.
docs/source/tagset/elemento-contrib.rst 
docs/source/tagset/elemento-fn.rst                                                                      docs/source/tagset/elemento-person-group.rst                                                            docs/source/tagset/elemento-surname.rst  
NA
NA.
#890
NA
> Corrigir regra disponível em contrib para contrib-type

- docs/source/index.rst
- docs/source/narr/parecer-aberto.rst
- docs/source/narr/scielo-brasil.rst
- docs/source/reference.rst
- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-contrib.rst
- docs/source/tagset/elemento-date.rst
- docs/source/tagset/elemento-sub-article.rst
Documentar revisão por pareceres aberta (OPR).
Novo: docs/source/narr/parecer-aberto.rst 
Modificações:
docs/source/narr/scielo-brasil.rst                                                                          docs/source/reference.rst                                                                                  docs/source/tagset/elemento-article.rst                                                                     docs/source/tagset/elemento-contrib.rst                                                                    docs/source/tagset/elemento-date.rst                                                                        docs/source/tagset/elemento-sub-article.rst 
NA
NA
#791
NA
> Documentação de revisão por pareceres aberta (OPR)

- docs/source/index.rst
- docs/source/narr/parecer-aberto.rst
- docs/source/narr/tipos-especiais-documentos.rst
Corrige a crase
na crase
regra gramatical da crase
NA
#791
NA
> Correção DA CRASE

- docs/source/narr/scielo-brasil.rst
- docs/source/tagset/elemento-article.rst
- docs/source/tagset/elemento-related-article.rst
Adiciona tipo de documento Adendo
article
related-article
regras para SciELO Brasil (Notas)
N/A
N/A
#908
N/A
> Adicionado tipo de documento Addendum em @article-type e @related-article-type #908

- docs/source/narr/parecer-aberto.rst
Aplica as modificações sugeridas no documento
https://docs.google.com/document/d/18ZiEUSqbxGlh0IprIUJF-N54m6ni7NXzVfjH9xc6DFw/edit?usp=sharing
n/a
n/a
n/a
n/a
https://docs.google.com/document/d/18ZiEUSqbxGlh0IprIUJF-N54m6ni7NXzVfjH9xc6DFw/edit?usp=sharing
> Altera documentação de parecer aberto
